### PR TITLE
accept date as parameter

### PR DESCRIPTION
**Pull request by LinusU**
This accepts a date to be passed in as the first parameter

### CODE REVIEW

**Comment by fredericosilva** [comment]
tks

**Comment by LinusU** [comment]
No problem, would you mind publishing a new version to npm? Thx

**Comment by fredericosilva** [comment]
It should be there already :)

**Comment by LinusU** [comment]
Ah yes, got confused since the `package.json` on Github still says `0.0.1`

**Comment by fredericosilva** [comment]
Fixed!

-- Frederico Silva

**Pull request merged**
